name: Daily Security Scan

on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Run scan
      run: |
        python3 scripts/day2_scan.py

    - name: Commit scan results
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add results/*
        git commit -m "Daily scan update"
        git push
      continue-on-error: true