name: Daily Security Scan


on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily at 3 AM UTC
  workflow_dispatch:

permissions:
    contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Run Nmap Scan
      run: |
        mkdir -p results
        TIMESTAMP=$(date + "%Y-%m-%d_%H-%M")
        sudo nmap -sS -T4 127.0.0.1 > results/scan_$TIMESTAMP.txt

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

    - name: Commit Results
      run: |
        git add results/
        git commit -m "Daily scan update" || echo "No Changes to commit"

    - name: Push to Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main