name: Daily System Info

on:
  schedule:
    - cron: "0 6 * * *"    # Runs daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Run Sysinfo Script
      run: |
        bash day2/sysinfo.sh > day2/sysinfo_output.txt

    - name: Commit Output
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add day2/sysinfo_output.txt
        git commit -m "Daily sysinfo update" || echo "Nothing to commit"

    - name: Push Changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main